/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { CreateRequestBuilderRequestsMetadata, CreateRequestBuilderUriTemplate, type CreateRequestBuilder } from './create/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organisations
 */
export interface OrganisationsRequestBuilder extends BaseRequestBuilder<OrganisationsRequestBuilder> {
    /**
     * The create property
     */
    get create(): CreateRequestBuilder;
    /**
     * Retrieve Organisations
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ArrayBuffer
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Retrieve Organisations
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrganisationsRequestBuilderNavigationMetadata: Record<Exclude<keyof OrganisationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    create: {
        uriTemplate: CreateRequestBuilderUriTemplate,
        requestsMetadata: CreateRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OrganisationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        adapterMethodName: "sendPrimitiveAsync",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/**
 * Uri template for the request builder.
 */
export const OrganisationsRequestBuilderUriTemplate = "{+baseurl}/organisations";
/* tslint:enable */
/* eslint-enable */
