/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedCommentOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedCommentOutput, type ApiResponse, type UnifiedCommentOutput } from '../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface CommentsGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedCommentOutput;
}
/**
 * Builds and executes requests for operations under /ticketing/comments/{id}
 */
export interface CommentsItemRequestBuilder extends BaseRequestBuilder<CommentsItemRequestBuilder> {
    /**
     * Retrieve a comment from any connected Ticketing software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of CommentsGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<CommentsItemRequestBuilderGetQueryParameters> | undefined) : Promise<CommentsGetResponse | undefined>;
    /**
     * Retrieve a comment from any connected Ticketing software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CommentsItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a comment from any connected Ticketing software
 */
export interface CommentsItemRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Ticketing software.
     */
    remoteData?: boolean;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a CommentsGetResponse
 */
export function createCommentsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCommentsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoCommentsGetResponse(commentsGetResponse: Partial<CommentsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(commentsGetResponse),
        "data": n => { commentsGetResponse.data = n.getObjectValue<UnifiedCommentOutput>(createUnifiedCommentOutputFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeCommentsGetResponse(writer: SerializationWriter, commentsGetResponse: Partial<CommentsGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, commentsGetResponse)
    writer.writeObjectValue<UnifiedCommentOutput>("data", commentsGetResponse.data, serializeUnifiedCommentOutput);
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CommentsItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CommentsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createCommentsGetResponseFromDiscriminatorValue,
        queryParametersMapper: CommentsItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const CommentsItemRequestBuilderUriTemplate = "{+baseurl}/ticketing/comments/{id}{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
