/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { AttributeRequestBuilderRequestsMetadata, AttributeRequestBuilderUriTemplate, type AttributeRequestBuilder } from './attribute/';
import { DefineRequestBuilderRequestsMetadata, DefineRequestBuilderUriTemplate, type DefineRequestBuilder } from './define/';
import { EntitiesRequestBuilderRequestsMetadata, EntitiesRequestBuilderUriTemplate, type EntitiesRequestBuilder } from './entities/';
import { MapRequestBuilderRequestsMetadata, MapRequestBuilderUriTemplate, type MapRequestBuilder } from './map/';
import { PropertiesRequestBuilderRequestsMetadata, PropertiesRequestBuilderUriTemplate, type PropertiesRequestBuilder } from './properties/';
import { type ValueRequestBuilder, ValueRequestBuilderRequestsMetadata, ValueRequestBuilderUriTemplate } from './value/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /field-mapping
 */
export interface FieldMappingRequestBuilder extends BaseRequestBuilder<FieldMappingRequestBuilder> {
    /**
     * The attribute property
     */
    get attribute(): AttributeRequestBuilder;
    /**
     * The define property
     */
    get define(): DefineRequestBuilder;
    /**
     * The entities property
     */
    get entities(): EntitiesRequestBuilder;
    /**
     * The map property
     */
    get map(): MapRequestBuilder;
    /**
     * The properties property
     */
    get properties(): PropertiesRequestBuilder;
    /**
     * The value property
     */
    get value(): ValueRequestBuilder;
}
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FieldMappingRequestBuilderNavigationMetadata: Record<Exclude<keyof FieldMappingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    attribute: {
        uriTemplate: AttributeRequestBuilderUriTemplate,
        requestsMetadata: AttributeRequestBuilderRequestsMetadata,
    },
    define: {
        uriTemplate: DefineRequestBuilderUriTemplate,
        requestsMetadata: DefineRequestBuilderRequestsMetadata,
    },
    entities: {
        uriTemplate: EntitiesRequestBuilderUriTemplate,
        requestsMetadata: EntitiesRequestBuilderRequestsMetadata,
    },
    map: {
        uriTemplate: MapRequestBuilderUriTemplate,
        requestsMetadata: MapRequestBuilderRequestsMetadata,
    },
    properties: {
        uriTemplate: PropertiesRequestBuilderUriTemplate,
        requestsMetadata: PropertiesRequestBuilderRequestsMetadata,
    },
    value: {
        uriTemplate: ValueRequestBuilderUriTemplate,
        requestsMetadata: ValueRequestBuilderRequestsMetadata,
    },
};
/**
 * Uri template for the request builder.
 */
export const FieldMappingRequestBuilderUriTemplate = "{+baseurl}/field-mapping";
/* tslint:enable */
/* eslint-enable */
