/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { CompaniesRequestBuilderNavigationMetadata, CompaniesRequestBuilderRequestsMetadata, CompaniesRequestBuilderUriTemplate, type CompaniesRequestBuilder } from './companies/';
import { ContactsRequestBuilderNavigationMetadata, ContactsRequestBuilderRequestsMetadata, ContactsRequestBuilderUriTemplate, type ContactsRequestBuilder } from './contacts/';
import { DealsRequestBuilderNavigationMetadata, DealsRequestBuilderRequestsMetadata, DealsRequestBuilderUriTemplate, type DealsRequestBuilder } from './deals/';
import { EngagementsRequestBuilderNavigationMetadata, EngagementsRequestBuilderRequestsMetadata, EngagementsRequestBuilderUriTemplate, type EngagementsRequestBuilder } from './engagements/';
import { NotesRequestBuilderNavigationMetadata, NotesRequestBuilderRequestsMetadata, NotesRequestBuilderUriTemplate, type NotesRequestBuilder } from './notes/';
import { StagesRequestBuilderNavigationMetadata, StagesRequestBuilderRequestsMetadata, StagesRequestBuilderUriTemplate, type StagesRequestBuilder } from './stages/';
import { TasksRequestBuilderNavigationMetadata, TasksRequestBuilderRequestsMetadata, TasksRequestBuilderUriTemplate, type TasksRequestBuilder } from './tasks/';
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata, UsersRequestBuilderRequestsMetadata, UsersRequestBuilderUriTemplate } from './users/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /crm
 */
export interface CrmRequestBuilder extends BaseRequestBuilder<CrmRequestBuilder> {
    /**
     * The companies property
     */
    get companies(): CompaniesRequestBuilder;
    /**
     * The contacts property
     */
    get contacts(): ContactsRequestBuilder;
    /**
     * The deals property
     */
    get deals(): DealsRequestBuilder;
    /**
     * The engagements property
     */
    get engagements(): EngagementsRequestBuilder;
    /**
     * The notes property
     */
    get notes(): NotesRequestBuilder;
    /**
     * The stages property
     */
    get stages(): StagesRequestBuilder;
    /**
     * The tasks property
     */
    get tasks(): TasksRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
}
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CrmRequestBuilderNavigationMetadata: Record<Exclude<keyof CrmRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    companies: {
        uriTemplate: CompaniesRequestBuilderUriTemplate,
        requestsMetadata: CompaniesRequestBuilderRequestsMetadata,
        navigationMetadata: CompaniesRequestBuilderNavigationMetadata,
    },
    contacts: {
        uriTemplate: ContactsRequestBuilderUriTemplate,
        requestsMetadata: ContactsRequestBuilderRequestsMetadata,
        navigationMetadata: ContactsRequestBuilderNavigationMetadata,
    },
    deals: {
        uriTemplate: DealsRequestBuilderUriTemplate,
        requestsMetadata: DealsRequestBuilderRequestsMetadata,
        navigationMetadata: DealsRequestBuilderNavigationMetadata,
    },
    engagements: {
        uriTemplate: EngagementsRequestBuilderUriTemplate,
        requestsMetadata: EngagementsRequestBuilderRequestsMetadata,
        navigationMetadata: EngagementsRequestBuilderNavigationMetadata,
    },
    notes: {
        uriTemplate: NotesRequestBuilderUriTemplate,
        requestsMetadata: NotesRequestBuilderRequestsMetadata,
        navigationMetadata: NotesRequestBuilderNavigationMetadata,
    },
    stages: {
        uriTemplate: StagesRequestBuilderUriTemplate,
        requestsMetadata: StagesRequestBuilderRequestsMetadata,
        navigationMetadata: StagesRequestBuilderNavigationMetadata,
    },
    tasks: {
        uriTemplate: TasksRequestBuilderUriTemplate,
        requestsMetadata: TasksRequestBuilderRequestsMetadata,
        navigationMetadata: TasksRequestBuilderNavigationMetadata,
    },
    users: {
        uriTemplate: UsersRequestBuilderUriTemplate,
        requestsMetadata: UsersRequestBuilderRequestsMetadata,
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
};
/**
 * Uri template for the request builder.
 */
export const CrmRequestBuilderUriTemplate = "{+baseurl}/crm";
/* tslint:enable */
/* eslint-enable */
