/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { CallbackRequestBuilderRequestsMetadata, CallbackRequestBuilderUriTemplate, type CallbackRequestBuilder } from './callback/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /connections/oauth
 */
export interface OauthRequestBuilder extends BaseRequestBuilder<OauthRequestBuilder> {
    /**
     * The callback property
     */
    get callback(): CallbackRequestBuilder;
}
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OauthRequestBuilderNavigationMetadata: Record<Exclude<keyof OauthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    callback: {
        uriTemplate: CallbackRequestBuilderUriTemplate,
        requestsMetadata: CallbackRequestBuilderRequestsMetadata,
    },
};
/**
 * Uri template for the request builder.
 */
export const OauthRequestBuilderUriTemplate = "{+baseurl}/connections/oauth";
/* tslint:enable */
/* eslint-enable */
