/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedCompanyOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedCompanyOutput, type ApiResponse, type UnifiedCompanyOutput } from '../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface CompaniesGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedCompanyOutput;
}
/**
 * Builds and executes requests for operations under /crm/companies/{id}
 */
export interface CompaniesItemRequestBuilder extends BaseRequestBuilder<CompaniesItemRequestBuilder> {
    /**
     * Retrieve a company from any connected Crm software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of CompaniesGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<CompaniesItemRequestBuilderGetQueryParameters> | undefined) : Promise<CompaniesGetResponse | undefined>;
    /**
     * Retrieve a company from any connected Crm software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CompaniesItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a company from any connected Crm software
 */
export interface CompaniesItemRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Crm software.
     */
    remoteData?: boolean;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a CompaniesGetResponse
 */
export function createCompaniesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCompaniesGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoCompaniesGetResponse(companiesGetResponse: Partial<CompaniesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(companiesGetResponse),
        "data": n => { companiesGetResponse.data = n.getObjectValue<UnifiedCompanyOutput>(createUnifiedCompanyOutputFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeCompaniesGetResponse(writer: SerializationWriter, companiesGetResponse: Partial<CompaniesGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, companiesGetResponse)
    writer.writeObjectValue<UnifiedCompanyOutput>("data", companiesGetResponse.data, serializeUnifiedCompanyOutput);
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CompaniesItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CompaniesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createCompaniesGetResponseFromDiscriminatorValue,
        queryParametersMapper: CompaniesItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const CompaniesItemRequestBuilderUriTemplate = "{+baseurl}/crm/companies/{id}{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
