/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { AccountsRequestBuilderNavigationMetadata, AccountsRequestBuilderRequestsMetadata, AccountsRequestBuilderUriTemplate, type AccountsRequestBuilder } from './accounts/';
import { AttachmentsRequestBuilderNavigationMetadata, AttachmentsRequestBuilderRequestsMetadata, AttachmentsRequestBuilderUriTemplate, type AttachmentsRequestBuilder } from './attachments/';
import { CommentsRequestBuilderNavigationMetadata, CommentsRequestBuilderRequestsMetadata, CommentsRequestBuilderUriTemplate, type CommentsRequestBuilder } from './comments/';
import { ContactsRequestBuilderNavigationMetadata, ContactsRequestBuilderRequestsMetadata, ContactsRequestBuilderUriTemplate, type ContactsRequestBuilder } from './contacts/';
import { TagsRequestBuilderNavigationMetadata, TagsRequestBuilderRequestsMetadata, TagsRequestBuilderUriTemplate, type TagsRequestBuilder } from './tags/';
import { TeamsRequestBuilderNavigationMetadata, TeamsRequestBuilderRequestsMetadata, TeamsRequestBuilderUriTemplate, type TeamsRequestBuilder } from './teams/';
import { TicketsRequestBuilderNavigationMetadata, TicketsRequestBuilderRequestsMetadata, TicketsRequestBuilderUriTemplate, type TicketsRequestBuilder } from './tickets/';
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata, UsersRequestBuilderRequestsMetadata, UsersRequestBuilderUriTemplate } from './users/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ticketing
 */
export interface TicketingRequestBuilder extends BaseRequestBuilder<TicketingRequestBuilder> {
    /**
     * The accounts property
     */
    get accounts(): AccountsRequestBuilder;
    /**
     * The attachments property
     */
    get attachments(): AttachmentsRequestBuilder;
    /**
     * The comments property
     */
    get comments(): CommentsRequestBuilder;
    /**
     * The contacts property
     */
    get contacts(): ContactsRequestBuilder;
    /**
     * The tags property
     */
    get tags(): TagsRequestBuilder;
    /**
     * The teams property
     */
    get teams(): TeamsRequestBuilder;
    /**
     * The tickets property
     */
    get tickets(): TicketsRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
}
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TicketingRequestBuilderNavigationMetadata: Record<Exclude<keyof TicketingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    accounts: {
        uriTemplate: AccountsRequestBuilderUriTemplate,
        requestsMetadata: AccountsRequestBuilderRequestsMetadata,
        navigationMetadata: AccountsRequestBuilderNavigationMetadata,
    },
    attachments: {
        uriTemplate: AttachmentsRequestBuilderUriTemplate,
        requestsMetadata: AttachmentsRequestBuilderRequestsMetadata,
        navigationMetadata: AttachmentsRequestBuilderNavigationMetadata,
    },
    comments: {
        uriTemplate: CommentsRequestBuilderUriTemplate,
        requestsMetadata: CommentsRequestBuilderRequestsMetadata,
        navigationMetadata: CommentsRequestBuilderNavigationMetadata,
    },
    contacts: {
        uriTemplate: ContactsRequestBuilderUriTemplate,
        requestsMetadata: ContactsRequestBuilderRequestsMetadata,
        navigationMetadata: ContactsRequestBuilderNavigationMetadata,
    },
    tags: {
        uriTemplate: TagsRequestBuilderUriTemplate,
        requestsMetadata: TagsRequestBuilderRequestsMetadata,
        navigationMetadata: TagsRequestBuilderNavigationMetadata,
    },
    teams: {
        uriTemplate: TeamsRequestBuilderUriTemplate,
        requestsMetadata: TeamsRequestBuilderRequestsMetadata,
        navigationMetadata: TeamsRequestBuilderNavigationMetadata,
    },
    tickets: {
        uriTemplate: TicketsRequestBuilderUriTemplate,
        requestsMetadata: TicketsRequestBuilderRequestsMetadata,
        navigationMetadata: TicketsRequestBuilderNavigationMetadata,
    },
    users: {
        uriTemplate: UsersRequestBuilderUriTemplate,
        requestsMetadata: UsersRequestBuilderRequestsMetadata,
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
};
/**
 * Uri template for the request builder.
 */
export const TicketingRequestBuilderUriTemplate = "{+baseurl}/ticketing";
/* tslint:enable */
/* eslint-enable */
