/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedStageOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedStageOutput, type ApiResponse, type UnifiedStageOutput } from '../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a StagesGetResponse
 */
export function createStagesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStagesGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoStagesGetResponse(stagesGetResponse: Partial<StagesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(stagesGetResponse),
        "data": n => { stagesGetResponse.data = n.getObjectValue<UnifiedStageOutput>(createUnifiedStageOutputFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeStagesGetResponse(writer: SerializationWriter, stagesGetResponse: Partial<StagesGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, stagesGetResponse)
    writer.writeObjectValue<UnifiedStageOutput>("data", stagesGetResponse.data, serializeUnifiedStageOutput);
}
export interface StagesGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedStageOutput;
}
/**
 * Builds and executes requests for operations under /crm/stages/{id}
 */
export interface StagesItemRequestBuilder extends BaseRequestBuilder<StagesItemRequestBuilder> {
    /**
     * Retrieve a stage from any connected Crm software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of StagesGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<StagesItemRequestBuilderGetQueryParameters> | undefined) : Promise<StagesGetResponse | undefined>;
    /**
     * Retrieve a stage from any connected Crm software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StagesItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a stage from any connected Crm software
 */
export interface StagesItemRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Crm software.
     */
    remoteData?: boolean;
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const StagesItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const StagesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createStagesGetResponseFromDiscriminatorValue,
        queryParametersMapper: StagesItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const StagesItemRequestBuilderUriTemplate = "{+baseurl}/crm/stages/{id}{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
