/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /magic-link/single
 */
export interface SingleRequestBuilder extends BaseRequestBuilder<SingleRequestBuilder> {
    /**
     * Retrieve a Magic Link
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ArrayBuffer
     */
     get(requestConfiguration?: RequestConfiguration<SingleRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Retrieve a Magic Link
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SingleRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a Magic Link
 */
export interface SingleRequestBuilderGetQueryParameters {
    id?: string;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const SingleRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        adapterMethodName: "sendPrimitiveAsync",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/**
 * Uri template for the request builder.
 */
export const SingleRequestBuilderUriTemplate = "{+baseurl}/magic-link/single?id={id}";
/* tslint:enable */
/* eslint-enable */
