/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { OauthRequestBuilderNavigationMetadata, OauthRequestBuilderUriTemplate, type OauthRequestBuilder } from './oauth/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /connections
 */
export interface ConnectionsRequestBuilder extends BaseRequestBuilder<ConnectionsRequestBuilder> {
    /**
     * The oauth property
     */
    get oauth(): OauthRequestBuilder;
    /**
     * List Connections
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ArrayBuffer
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * List Connections
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConnectionsRequestBuilderNavigationMetadata: Record<Exclude<keyof ConnectionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    oauth: {
        uriTemplate: OauthRequestBuilderUriTemplate,
        navigationMetadata: OauthRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ConnectionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        adapterMethodName: "sendPrimitiveAsync",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/**
 * Uri template for the request builder.
 */
export const ConnectionsRequestBuilderUriTemplate = "{+baseurl}/connections";
/* tslint:enable */
/* eslint-enable */
