/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedStageOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedStageOutput, type ApiResponse, type UnifiedStageOutput } from '../../models/';
import { StagesItemRequestBuilderRequestsMetadata, StagesItemRequestBuilderUriTemplate, type StagesItemRequestBuilder } from './item/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a stagesGetResponse
 */
export function createStagesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStagesGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoStagesGetResponse(stagesGetResponse: Partial<StagesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(stagesGetResponse),
        "data": n => { stagesGetResponse.data = n.getObjectValue<UnifiedStageOutput>(createUnifiedStageOutputFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeStagesGetResponse(writer: SerializationWriter, stagesGetResponse: Partial<StagesGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, stagesGetResponse)
    writer.writeObjectValue<UnifiedStageOutput>("data", stagesGetResponse.data, serializeUnifiedStageOutput);
}
export interface StagesGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedStageOutput;
}
/**
 * Builds and executes requests for operations under /crm/stages
 */
export interface StagesRequestBuilder extends BaseRequestBuilder<StagesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.crm.stages.item collection
     * @param id id of the stage you want to retrieve.
     * @returns a StagesItemRequestBuilder
     */
     byId(id: string) : StagesItemRequestBuilder;
    /**
     * List a batch of Stages
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of StagesGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<StagesRequestBuilderGetQueryParameters> | undefined) : Promise<StagesGetResponse | undefined>;
    /**
     * List a batch of Stages
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StagesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * List a batch of Stages
 */
export interface StagesRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Crm software.
     */
    remoteData?: boolean;
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const StagesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StagesRequestBuilderNavigationMetadata: Record<Exclude<keyof StagesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        uriTemplate: StagesItemRequestBuilderUriTemplate,
        requestsMetadata: StagesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const StagesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createStagesGetResponseFromDiscriminatorValue,
        queryParametersMapper: StagesRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const StagesRequestBuilderUriTemplate = "{+baseurl}/crm/stages{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
