/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedContactOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedContactOutput, type ApiResponse, type UnifiedContactOutput } from '../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ContactsGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedContactOutput;
}
/**
 * Builds and executes requests for operations under /crm/contacts/{id}
 */
export interface ContactsItemRequestBuilder extends BaseRequestBuilder<ContactsItemRequestBuilder> {
    /**
     * Retrieve a contact from any connected CRM
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ContactsGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<ContactsItemRequestBuilderGetQueryParameters> | undefined) : Promise<ContactsGetResponse | undefined>;
    /**
     * Retrieve a contact from any connected CRM
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ContactsItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a contact from any connected CRM
 */
export interface ContactsItemRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original CRM software.
     */
    remoteData?: boolean;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a ContactsGetResponse
 */
export function createContactsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoContactsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoContactsGetResponse(contactsGetResponse: Partial<ContactsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(contactsGetResponse),
        "data": n => { contactsGetResponse.data = n.getObjectValue<UnifiedContactOutput>(createUnifiedContactOutputFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeContactsGetResponse(writer: SerializationWriter, contactsGetResponse: Partial<ContactsGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, contactsGetResponse)
    writer.writeObjectValue<UnifiedContactOutput>("data", contactsGetResponse.data, serializeUnifiedContactOutput);
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ContactsItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ContactsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createContactsGetResponseFromDiscriminatorValue,
        queryParametersMapper: ContactsItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const ContactsItemRequestBuilderUriTemplate = "{+baseurl}/crm/contacts/{id}{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
