/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedAttachmentOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedAttachmentOutput, type ApiResponse, type UnifiedAttachmentOutput } from '../../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a downloadGetResponse
 */
export function createDownloadGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoDownloadGetResponse(downloadGetResponse: Partial<DownloadGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(downloadGetResponse),
        "data": n => { downloadGetResponse.data = n.getObjectValue<UnifiedAttachmentOutput>(createUnifiedAttachmentOutputFromDiscriminatorValue); },
    }
}
export interface DownloadGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedAttachmentOutput;
}
/**
 * Builds and executes requests for operations under /ticketing/attachments/{id}/download
 */
export interface DownloadRequestBuilder extends BaseRequestBuilder<DownloadRequestBuilder> {
    /**
     * Download a attachment from any connected Ticketing software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of DownloadGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<DownloadRequestBuilderGetQueryParameters> | undefined) : Promise<DownloadGetResponse | undefined>;
    /**
     * Download a attachment from any connected Ticketing software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DownloadRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Download a attachment from any connected Ticketing software
 */
export interface DownloadRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Ticketing software.
     */
    remoteData?: boolean;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeDownloadGetResponse(writer: SerializationWriter, downloadGetResponse: Partial<DownloadGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, downloadGetResponse)
    writer.writeObjectValue<UnifiedAttachmentOutput>("data", downloadGetResponse.data, serializeUnifiedAttachmentOutput);
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const DownloadRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DownloadRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createDownloadGetResponseFromDiscriminatorValue,
        queryParametersMapper: DownloadRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const DownloadRequestBuilderUriTemplate = "{+baseurl}/ticketing/attachments/{id}/download{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
