/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { serializeApiKeyDto, type ApiKeyDto } from '../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth/generate-apikey
 */
export interface GenerateApikeyRequestBuilder extends BaseRequestBuilder<GenerateApikeyRequestBuilder> {
    /**
     * Create API Key
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: ApiKeyDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Create API Key
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPostRequestInformation(body: ApiKeyDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const GenerateApikeyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        adapterMethodName: "sendNoResponseContentAsync",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeApiKeyDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const GenerateApikeyRequestBuilderUriTemplate = "{+baseurl}/auth/generate-apikey";
/* tslint:enable */
/* eslint-enable */
