/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedTaskOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedTaskOutput, type ApiResponse, type UnifiedTaskOutput } from '../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a TasksGetResponse
 */
export function createTasksGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTasksGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoTasksGetResponse(tasksGetResponse: Partial<TasksGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(tasksGetResponse),
        "data": n => { tasksGetResponse.data = n.getObjectValue<UnifiedTaskOutput>(createUnifiedTaskOutputFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeTasksGetResponse(writer: SerializationWriter, tasksGetResponse: Partial<TasksGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, tasksGetResponse)
    writer.writeObjectValue<UnifiedTaskOutput>("data", tasksGetResponse.data, serializeUnifiedTaskOutput);
}
export interface TasksGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedTaskOutput;
}
/**
 * Builds and executes requests for operations under /crm/tasks/{id}
 */
export interface TasksItemRequestBuilder extends BaseRequestBuilder<TasksItemRequestBuilder> {
    /**
     * Retrieve a task from any connected Crm software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of TasksGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<TasksItemRequestBuilderGetQueryParameters> | undefined) : Promise<TasksGetResponse | undefined>;
    /**
     * Retrieve a task from any connected Crm software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TasksItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a task from any connected Crm software
 */
export interface TasksItemRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Crm software.
     */
    remoteData?: boolean;
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const TasksItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TasksItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createTasksGetResponseFromDiscriminatorValue,
        queryParametersMapper: TasksItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const TasksItemRequestBuilderUriTemplate = "{+baseurl}/crm/tasks/{id}{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
