/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedTicketOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedTicketOutput, type ApiResponse, type UnifiedTicketOutput } from '../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a TicketsGetResponse
 */
export function createTicketsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTicketsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoTicketsGetResponse(ticketsGetResponse: Partial<TicketsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(ticketsGetResponse),
        "data": n => { ticketsGetResponse.data = n.getObjectValue<UnifiedTicketOutput>(createUnifiedTicketOutputFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeTicketsGetResponse(writer: SerializationWriter, ticketsGetResponse: Partial<TicketsGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, ticketsGetResponse)
    writer.writeObjectValue<UnifiedTicketOutput>("data", ticketsGetResponse.data, serializeUnifiedTicketOutput);
}
export interface TicketsGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedTicketOutput;
}
/**
 * Builds and executes requests for operations under /ticketing/tickets/{id}
 */
export interface TicketsItemRequestBuilder extends BaseRequestBuilder<TicketsItemRequestBuilder> {
    /**
     * Retrieve a ticket from any connected Ticketing software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of TicketsGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<TicketsItemRequestBuilderGetQueryParameters> | undefined) : Promise<TicketsGetResponse | undefined>;
    /**
     * Retrieve a ticket from any connected Ticketing software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TicketsItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a ticket from any connected Ticketing software
 */
export interface TicketsItemRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Ticketing software.
     */
    remoteData?: boolean;
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const TicketsItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TicketsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createTicketsGetResponseFromDiscriminatorValue,
        queryParametersMapper: TicketsItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const TicketsItemRequestBuilderUriTemplate = "{+baseurl}/ticketing/tickets/{id}{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
