/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedEngagementOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedEngagementOutput, type ApiResponse, type UnifiedEngagementOutput } from '../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a EngagementsGetResponse
 */
export function createEngagementsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEngagementsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoEngagementsGetResponse(engagementsGetResponse: Partial<EngagementsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(engagementsGetResponse),
        "data": n => { engagementsGetResponse.data = n.getObjectValue<UnifiedEngagementOutput>(createUnifiedEngagementOutputFromDiscriminatorValue); },
    }
}
export interface EngagementsGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedEngagementOutput;
}
/**
 * Builds and executes requests for operations under /crm/engagements/{id}
 */
export interface EngagementsItemRequestBuilder extends BaseRequestBuilder<EngagementsItemRequestBuilder> {
    /**
     * Retrieve a engagement from any connected Crm software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of EngagementsGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<EngagementsItemRequestBuilderGetQueryParameters> | undefined) : Promise<EngagementsGetResponse | undefined>;
    /**
     * Retrieve a engagement from any connected Crm software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<EngagementsItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a engagement from any connected Crm software
 */
export interface EngagementsItemRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Crm software.
     */
    remoteData?: boolean;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeEngagementsGetResponse(writer: SerializationWriter, engagementsGetResponse: Partial<EngagementsGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, engagementsGetResponse)
    writer.writeObjectValue<UnifiedEngagementOutput>("data", engagementsGetResponse.data, serializeUnifiedEngagementOutput);
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const EngagementsItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const EngagementsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createEngagementsGetResponseFromDiscriminatorValue,
        queryParametersMapper: EngagementsItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const EngagementsItemRequestBuilderUriTemplate = "{+baseurl}/crm/engagements/{id}{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
