/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { ApiKeysRequestBuilderRequestsMetadata, ApiKeysRequestBuilderUriTemplate, type ApiKeysRequestBuilder } from './apiKeys/';
import { GenerateApikeyRequestBuilderRequestsMetadata, GenerateApikeyRequestBuilderUriTemplate, type GenerateApikeyRequestBuilder } from './generateApikey/';
import { LoginRequestBuilderRequestsMetadata, LoginRequestBuilderUriTemplate, type LoginRequestBuilder } from './login/';
import { RegisterRequestBuilderRequestsMetadata, RegisterRequestBuilderUriTemplate, type RegisterRequestBuilder } from './register/';
import { type UsersRequestBuilder, UsersRequestBuilderRequestsMetadata, UsersRequestBuilderUriTemplate } from './users/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The apiKeys property
     */
    get apiKeys(): ApiKeysRequestBuilder;
    /**
     * The generateApikey property
     */
    get generateApikey(): GenerateApikeyRequestBuilder;
    /**
     * The login property
     */
    get login(): LoginRequestBuilder;
    /**
     * The register property
     */
    get register(): RegisterRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
}
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    apiKeys: {
        uriTemplate: ApiKeysRequestBuilderUriTemplate,
        requestsMetadata: ApiKeysRequestBuilderRequestsMetadata,
    },
    generateApikey: {
        uriTemplate: GenerateApikeyRequestBuilderUriTemplate,
        requestsMetadata: GenerateApikeyRequestBuilderRequestsMetadata,
    },
    login: {
        uriTemplate: LoginRequestBuilderUriTemplate,
        requestsMetadata: LoginRequestBuilderRequestsMetadata,
    },
    register: {
        uriTemplate: RegisterRequestBuilderUriTemplate,
        requestsMetadata: RegisterRequestBuilderRequestsMetadata,
    },
    users: {
        uriTemplate: UsersRequestBuilderUriTemplate,
        requestsMetadata: UsersRequestBuilderRequestsMetadata,
    },
};
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/auth";
/* tslint:enable */
/* eslint-enable */
