/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { serializeDefineTargetFieldDto, type DefineTargetFieldDto } from '../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /field-mapping/define
 */
export interface DefineRequestBuilder extends BaseRequestBuilder<DefineRequestBuilder> {
    /**
     * Define target Field
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: DefineTargetFieldDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Define target Field
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPostRequestInformation(body: DefineTargetFieldDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const DefineRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        adapterMethodName: "sendNoResponseContentAsync",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDefineTargetFieldDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const DefineRequestBuilderUriTemplate = "{+baseurl}/field-mapping/define";
/* tslint:enable */
/* eslint-enable */
