/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createPassThroughResponseFromDiscriminatorValue, serializePassThroughRequestDto, serializePassThroughResponse, type PassThroughRequestDto, type PassThroughResponse } from '../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /passthrough
 */
export interface PassthroughRequestBuilder extends BaseRequestBuilder<PassthroughRequestBuilder> {
    /**
     * Make a passthrough request
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of PassThroughResponse
     */
     post(body: PassThroughRequestDto, requestConfiguration?: RequestConfiguration<PassthroughRequestBuilderPostQueryParameters> | undefined) : Promise<PassThroughResponse | undefined>;
    /**
     * Make a passthrough request
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPostRequestInformation(body: PassThroughRequestDto, requestConfiguration?: RequestConfiguration<PassthroughRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Make a passthrough request
 */
export interface PassthroughRequestBuilderPostQueryParameters {
    integrationId?: string;
    linkedUserId?: string;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const PassthroughRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createPassThroughResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePassThroughRequestDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const PassthroughRequestBuilderUriTemplate = "{+baseurl}/passthrough?integrationId={integrationId}&linkedUserId={linkedUserId}";
/* tslint:enable */
/* eslint-enable */
