/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createUnifiedTeamOutputFromDiscriminatorValue, deserializeIntoApiResponse, serializeApiResponse, serializeUnifiedTeamOutput, type ApiResponse, type UnifiedTeamOutput } from '../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a TeamsGetResponse
 */
export function createTeamsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTeamsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoTeamsGetResponse(teamsGetResponse: Partial<TeamsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoApiResponse(teamsGetResponse),
        "data": n => { teamsGetResponse.data = n.getObjectValue<UnifiedTeamOutput>(createUnifiedTeamOutputFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeTeamsGetResponse(writer: SerializationWriter, teamsGetResponse: Partial<TeamsGetResponse> | undefined = {}) : void {
    serializeApiResponse(writer, teamsGetResponse)
    writer.writeObjectValue<UnifiedTeamOutput>("data", teamsGetResponse.data, serializeUnifiedTeamOutput);
}
export interface TeamsGetResponse extends ApiResponse, Parsable {
    /**
     * The data property
     */
    data?: UnifiedTeamOutput;
}
/**
 * Builds and executes requests for operations under /ticketing/teams/{id}
 */
export interface TeamsItemRequestBuilder extends BaseRequestBuilder<TeamsItemRequestBuilder> {
    /**
     * Retrieve a team from any connected Ticketing software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of TeamsGetResponse
     */
     get(requestConfiguration?: RequestConfiguration<TeamsItemRequestBuilderGetQueryParameters> | undefined) : Promise<TeamsGetResponse | undefined>;
    /**
     * Retrieve a team from any connected Ticketing software
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TeamsItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve a team from any connected Ticketing software
 */
export interface TeamsItemRequestBuilderGetQueryParameters {
    /**
     * Set to true to include data from the original Ticketing software.
     */
    remoteData?: boolean;
}
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const TeamsItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "remoteData": "remote_data",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TeamsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createTeamsGetResponseFromDiscriminatorValue,
        queryParametersMapper: TeamsItemRequestBuilderGetQueryParametersMapper,
    },
};
/**
 * Uri template for the request builder.
 */
export const TeamsItemRequestBuilderUriTemplate = "{+baseurl}/ticketing/teams/{id}{?remote_data*}";
/* tslint:enable */
/* eslint-enable */
